AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Update pipeline for gfe-db
Resources:
  gfedbUpdatePipelineStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Name: gfe-db-update-pipeline
      DefinitionUri: statemachine/pipeline.asl.json
      # Role: arn:aws:iam::531868584498:role/StepFunctionsLambdaRole
      # DefinitionSubstitutions:
      #   startBuildInstanceFunctionArn: !GetAtt startBuildInstanceFunction.Arn
      #   stopBuildInstanceFunctionArn: !GetAtt stopBuildInstanceFunction.Arn
      #   loadGFEdbFunctionArn: !GetAtt loadGFEdbFunction.Arn
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref gfeDBBuildStackTopic
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref startBuildInstanceFunction
      #   - LambdaInvokePolicy:
      #       FunctionName: !Ref stopBuildInstanceFunction
      #   - LambdaInvokePolicy:
      #       FunctionName: !Ref loadGFEdbFunction
  startBuildInstanceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/startBuildInstance/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 60
  # stopBuildInstanceFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/stopBuildInstance/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8
  # loadGFEdbFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/loadGFEdb/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8

    gfeDBBuildStackSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !Ref
        Protocol: lambda
        TopicArn: !Ref gfeDBBuildStackTopic
Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  gfedbUpdatePipelineStateMachineArn:
    Description: "gfe-db update pipeline ARN"
    Value: !Ref gfedbUpdatePipelineStateMachine
  # gfedbUpdatePipelineStateMachineRoleArn:
  #   Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
  #   Value: !GetAtt gfedbUpdatePipelineStateMachineRole.Arn
