AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Update pipeline for gfe-db
Resources:
  startBuildInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        PolicyName: startBuildInstancePolicy
        PolicyDocument:
          - 



  startBuildInstanceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/startBuildInstance/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 60
      Events:
        startBuildEvent:
          Type: SNS
          Properties:
            Topic: !Ref startBuildTopic


### build and deploy
### publish to startBuild to trigger build
### add lines to build script to publish to stopBuildInstance when finished with build
###
      
  # stopBuildInstanceFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/stopBuildInstance/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8
  # loadGFEdbFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/loadGFEdb/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8

