AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Update pipeline for gfe-db
Resources:
  startBuildTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "gfe-db-start-build"
  loadGFEdbTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "gfe-db-load-database"
  startBuildInstanceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/startBuildInstance/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 60
      Events:
        Type: SNS
        Properties:
          Topic: !Ref loadGFEdbTopic

### build and deploy
### publish to startBuild to trigger build
### add lines to build script to publish to loadGFE when finished with build
###
      
  # stopBuildInstanceFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/stopBuildInstance/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8
  # loadGFEdbFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/loadGFEdb/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8
Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  gfedbUpdatePipelineStateMachineArn:
    Description: "gfe-db update pipeline ARN"
    Value: !Ref gfedbUpdatePipelineStateMachine
  # gfedbUpdatePipelineStateMachineRoleArn:
  #   Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
  #   Value: !GetAtt gfedbUpdatePipelineStateMachineRole.Arn
