AWSTemplateFormatVersion: 2010-09-09
Description: Build service for GFE database
Parameters: 
  gfedbBuildKeyName:
    Type: String
    Default: gfe-build-service
    Description: Key pair name for the GFE build server instance.
    NoEcho: true
  gfedbBuildImageId:
    Type: String
    Default: ami-0d5eff06f840b45e9
  gfeVPC:
    Type: String
    Default: vpc-8a3d74f0
Resources: 
  gfedbBuildSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: gfedb-build-server-sg
      GroupDescription: Security group for the GFE DB build server
      VpcId: !Ref gfeVPC
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  gfedbBuildServer:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref gfedbBuildKeyName
      DisableApiTermination: false
      ImageId: !Ref gfedbBuildImageId
      InstanceType: c5d.large
      Monitoring: true
      SecurityGroupIds:
        - !Ref gfedbBuildSG
      UserData:
        Fn::Base64: |
          #!/bin/bash -x
          IDX=1
          for DEV in /dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_*-ns-1; do
            mkfs.xfs ${DEV}
            mkdir -p /local${IDX}
            echo ${DEV} /local${IDX} xfs defaults,noatime 1 2 >> /etc/fstab
            IDX=$((${IDX} + 1))
          done
          mount -a
      Tags:
        - Key: Name
          Value: gfe-build
Outputs:
  gfedbBuildServerPublicDNS:
    Description: Public DNS for SSH access into the build server
    Value: !GetAtt gfedbBuildServer.PublicDnsName