AWSTemplateFormatVersion: 2010-09-09
Description: Deploys gfe-db S3 bucket and SNS topics
Parameters: 
  AppName:
    Type: String
    Default: gfe-db
  gfedbBucketName:
    Type: String
    Default: 'gfe-db'
Resources: 
  gfedbBuildTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AppName}-build-topic'
      Subscription:
        - Protocol: sqs
          Endpoint: !GetAtt gfedbBuildQueue.Arn
  gfedbBuildTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Action: sns:Publish
          Resource: !Ref gfedbBuildTopic
          Condition:
            ArnLike:
              aws:SourceArn: !Sub 'arn:${AWS::Partition}:s3:::${gfedbBucketName}-${AWS::AccountId}'
      Topics:
        - !Ref gfedbBuildTopic
  gfedbBuildQueue:
    Type: AWS::SQS::Queue
  # loadGFEdbTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: "gfe-db-load-database"
  gfedbBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - gfedbBuildTopicPolicy
    Properties:
      BucketName: !Sub '${gfedbBucketName}-${AWS::AccountId}'
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Topic: !Ref gfedbBuildTopic
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: events/
                  - Name: suffix
                    Value: .json
Outputs:
  gfedbBucketName:
    Description: "S3 Bucket for gfe-db data and artifacts"
    Value: !Ref gfedbBucket
    Export:
      Name: !Sub '${AppName}-bucket-name'
  gfedbBucketArn:
    Description: "S3 Bucket ARN for gfe-db data and artifacts"
    Value: !GetAtt gfedbBucket.Arn
    Export:
      Name: !Sub '${AppName}-bucket-arn'
  gfedbBuildTopicName:
    Description: "SNS topic for starting the build service"
    Value: !GetAtt gfedbBuildTopic.TopicName
    Export:
      Name: !Sub '${AppName}-build-topic-name'
  gfedbBuildTopicArn:
    Description: "SNS topic ARN for starting the build service"
    Value: !Ref gfedbBuildTopic
    Export:
      Name: !Sub '${AppName}-build-topic-arn'
  gfedbBuildQueueUrl:
    Description: "SQS queue URL for the release version being built"
    Value: !Ref gfedbBuildQueue
    Export:
      Name: !Sub '${AppName}-build-queue-url'
  gfedbBuildQueueArn:
    Description: "SQS queue ARN for the release version being built"
    Value: !GetAtt gfedbBuildQueue.Arn
    Export:
      Name: !Sub '${AppName}-build-queue-arn'
